### ISSUE TITLE
Does not work anymore (1.18.2)

### ISSUE THREAD

**Issue by BrandonT80** [froobynooby/FarmControl#24]
Plugin no longer works in 1.18.2. Produces the below error:

[15:47:34] [Server thread/INFO]: [FarmControl] Enabling FarmControl v1.2.0
[15:47:34] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.froobworld.farmcontrol.lib.nabconfiguration.utils.InstantFallbackConfigurationSection.getSection(String, String)" because "this.fallbackSection" is null
[15:47:34] [Server thread/WARN]: 	at FarmControl-1.2.0.jar//com.froobworld.farmcontrol.lib.nabconfiguration.utils.InstantFallbackConfigurationSection.getSection(InstantFallbackConfigurationSection.java:36)
[15:47:34] [Server thread/WARN]: 	at FarmControl-1.2.0.jar//com.froobworld.farmcontrol.lib.nabconfiguration.ConfigSectionPopulator.populate(ConfigSectionPopulator.java:46)
[15:47:34] [Server thread/WARN]: 	at FarmControl-1.2.0.jar//com.froobworld.farmcontrol.lib.nabconfiguration.NabConfiguration.load(NabConfiguration.java:31)
[15:47:34] [Server thread/WARN]: 	at FarmControl-1.2.0.jar//com.froobworld.farmcontrol.FarmControl.onEnable(FarmControl.java:26)
[15:47:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:47:34] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:47:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[15:47:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[15:47:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[15:47:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[15:47:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[15:47:34] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[15:47:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[15:47:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[15:47:34] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:47:34] [Server thread/ERROR]: Error occurred while enabling FarmControl v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.froobworld.farmcontrol.lib.nabconfiguration.ConfigEntry.get()" is null
	at com.froobworld.farmcontrol.HookManager.load(HookManager.java:25) ~[FarmControl-1.2.0.jar:?]
	at com.froobworld.farmcontrol.FarmControl.onEnable(FarmControl.java:31) ~[FarmControl-1.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-274]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:47:34] [Server thread/INFO]: [FarmControl] Disabling FarmControl v1.2.0
[15:47:34] [Server thread/ERROR]: Error occurred while disabling FarmControl v1.2.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.froobworld.farmcontrol.controller.FarmController.unRegister()" because "this.farmController" is null
	at com.froobworld.farmcontrol.FarmControl.onDisable(FarmControl.java:75) ~[FarmControl-1.2.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-274]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by froobynooby** [comment]
Can you share a copy of your config? https://paste.gg/

**Comment by BrandonT80** [comment]
https://paste.gg/p/anonymous/8adc8b3d089745afb3592095d6c3df1d

**Comment by BrandonT80** [comment]
On that config, the 'default' was changed to the world name, if that helps?

**Comment by froobynooby** [comment]
Ah, that would be why it's giving you an error - the default section always needs to exist or the plugin can't operate. If you only want it that one world you would need to do something like this: https://paste.gg/p/anonymous/4caca14c17984c7ea3c0c0ee0447762a

**Comment by BrandonT80** [comment]
> 

That seemed to resolve the issue!
