### ISSUE TITLE
support folia 1.20.4

### ISSUE THREAD

**Issue by xiaoluofa** [froobynooby/FarmControl#41]
[22:40:19 ERROR]: Thread Region Scheduler Thread #1 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftStrider.getHandle(CraftStrider.java:77) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftStrider.getHandle(CraftStrider.java:8) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:939) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:393) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getEntitiesByClasses$4(CraftRegionAccessor.java:373) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getEntitiesByClasses(CraftRegionAccessor.java:362) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at com.froobworld.farmcontrol.controller.task.TriggerCheckTask.run(TriggerCheckTask.java:65) ~[FarmControl-1.2.5.jar:?]
        at com.froobworld.farmcontrol.hook.scheduler.RegionisedSchedulerHook.lambda$runRepeatingTask$1(RegionisedSchedulerHook.java:21) ~[FarmControl-1.2.5.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:40:19 WARN]: [FarmControl] Global task for FarmControl v1.2.5 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftStrider.getHandle(CraftStrider.java:77) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftStrider.getHandle(CraftStrider.java:8) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:939) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:393) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getEntitiesByClasses$4(CraftRegionAccessor.java:373) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getEntitiesByClasses(CraftRegionAccessor.java:362) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at com.froobworld.farmcontrol.controller.task.TriggerCheckTask.run(TriggerCheckTask.java:65) ~[FarmControl-1.2.5.jar:?]
        at com.froobworld.farmcontrol.hook.scheduler.RegionisedSchedulerHook.lambda$runRepeatingTask$1(RegionisedSchedulerHook.java:21) ~[FarmControl-1.2.5.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[luminol-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[luminol-1.20.4.jar:git-Luminol-"59a428e"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
>

**Comment by xiaoluofa** [comment]
> Hey, could you give this jar a go and let me know if you run into any issues [FarmControl.zip](https://github.com/froobynooby/FarmControl/files/14558799/FarmControl.zip)

thanks fixed
