### ISSUE TITLE
Folia Errors

### ISSUE THREAD

**Issue by Speedspencer** [froobynooby/FarmControl#44]
[23:40:47 WARN]: [FarmControl] Global task for FarmControl v1.2.5 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftWolf.getHandle(CraftWolf.java:35) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftWolf.getHandle(CraftWolf.java:7) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isInWorld(CraftEntity.java:939) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.isValid(CraftEntity.java:393) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.lambda$getEntitiesByClass$3(CraftRegionAccessor.java:350) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftRegionAccessor.getEntitiesByClass(CraftRegionAccessor.java:341) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.froobworld.farmcontrol.controller.task.TriggerCheckTask.run(TriggerCheckTask.java:65) ~[FarmControl-1.2.5.jar:?]
        at com.froobworld.farmcontrol.hook.scheduler.RegionisedSchedulerHook.lambda$runRepeatingTask$1(RegionisedSchedulerHook.java:21) ~[FarmControl-1.2.5.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
        at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by froobynooby** [comment]
Hey, this is fixed in the most recent dev build, you can download it here https://ci.froobworld.com/job/FarmControl/
